### ISSUE TITLE
Stacking map and not detection of horizontal translation

### ISSUE THREAD

**Issue by Alphastrick** [rsasaki0109/graphslam_ros2#32] opened 2022-02-25 09:14 UTC
I try to use slamming for a robot, but moving it will create some strange results.

Moving the robot vertically works fine, as lone as the robot does not move more than 5 meters at once. The transformation will be published correctly.
However moving it in horizontal direction the slamming will not match the input pointclouds.

Also if the map is visualized, the map looks like all inputs are stacked. 

![image](https://user-images.githubusercontent.com/19841837/155686883-354be5d0-ded7-4196-8577-ceb69e2cff3b.png)

To to resolve this, so that the scanmatcher will publish the correct transformation in horizontal direction and should the map look like this?

**Comment by shineyruan** [comment] 2022-03-03 08:00
I got the same problem. Really looking forward to a solution.

**Comment by rsasaki0109** [comment] 2022-03-03 09:56
Can you please provide rosbag the problem occurs?

**Comment by shineyruan** [comment] 2022-03-03 10:34
> Can you please provide rosbag the problem occurs?
> 
> 

Please take a look at this bag file: https://drive.google.com/drive/folders/1YhOkbZCRT3qyiIVc96_xJ-PSmSiQFvDr

**Comment by rsasaki0109** [comment] 2022-03-03 11:06
@shineyruan

The first image shows a map made pcd by "ros2 service call /map_save std_srvs/Empty" and displayed by cloudcompare.
The second image is the rviz screen. 
It seems that rviz is displaying something wrong. I had no problem with ros2 foxy, but I confirmed this problem with ros2 galactic. I'll try to find the cause.
![image](https://user-images.githubusercontent.com/18298605/156554872-831e8cfa-e1bf-456b-9a04-8a0c6ccc7f91.png)

![image](https://user-images.githubusercontent.com/18298605/156552584-d47b5b34-174d-4b46-acec-e3013e4f539f.png)


Since it is a small environment, the following parameters would be better.
```
scan_matcher:
  ros__parameters:
    global_frame_id: "map"
    robot_frame_id: "base_link"
    registration_method: "NDT"
    ndt_resolution: 1.0
    ndt_num_threads: 4
    gicp_corr_dist_threshold: 5.0
    trans_for_mapupdate: 1.5
    vg_size_for_input: 0.5
    vg_size_for_map: 0.05
    use_min_max_filter: true
    scan_min_range: 1.0
    scan_max_range: 200.0
    scan_period: 0.2
    map_publish_period: 15.0
    num_targeted_cloud: 20
    set_initial_pose: true
    initial_pose_x: 0.0
    initial_pose_y: 0.0
    initial_pose_z: 0.0
    initial_pose_qx: 0.0
    initial_pose_qy: 0.0
    initial_pose_qz: 0.0
    initial_pose_qw: 1.0
    use_imu: false
    use_odom: true
    debug_flag: false
```

**Comment by rsasaki0109** [comment] 2022-03-03 11:22
The following parameters would be good.
```
scan_matcher:
  ros__parameters:
    global_frame_id: "map"
    robot_frame_id: "base_link"
    registration_method: "NDT"
    ndt_resolution: 1.0
    ndt_num_threads: 4
    gicp_corr_dist_threshold: 5.0
    trans_for_mapupdate: 1.5
    vg_size_for_input: 0.5
    vg_size_for_map: 0.05
    use_min_max_filter: true
    scan_min_range: 1.0
    scan_max_range: 200.0
    scan_period: 0.2
    map_publish_period: 15.0
    num_targeted_cloud: 20
    set_initial_pose: true
    initial_pose_x: 0.0
    initial_pose_y: 0.0
    initial_pose_z: 0.0
    initial_pose_qx: 0.0
    initial_pose_qy: 0.0
    initial_pose_qz: 0.0
    initial_pose_qw: 1.0
    use_imu: false
    use_odom: true
    debug_flag: false
```

**Comment by Alphastrick** [comment] 2022-03-11 08:16
@rsasaki0109

Can you confirm that it is only some visualization bug? Unfortunately, I can not provide a bag file with my specific use case.

**Comment by rsasaki0109** [comment] 2022-03-11 08:48
@Alphastrick 
If the yellow path (/path ) in rviz looks OK, then it is a visualization problem.
Can you confirm what the trajectory of /path is in rviz?

**Comment by rsasaki0109** [comment] 2022-03-11 08:52
Also, the ndt parameters need to be changed, such as whether the measurement environment is indoors or outdoors, and the slam may be failing due to improper parameters.
The parameters in the sample(https://github.com/rsasaki0109/lidarslam_ros2/tree/foxy/lidarslam/param) are for outdoor use. If you are indoors, you may want to try the parameters listed above.
https://github.com/rsasaki0109/lidarslam_ros2/issues/32#issuecomment-1057932902

**Comment by rsasaki0109** [comment] 2022-08-18 01:31
I will close this issue at once. Please contact me if you have any further problems.

**Closed as completed by rsasaki0109** 2022-08-18 01:31 UTC
Labels: bug
